### ISSUE TITLE
vcpkg安装的1.4.1版本，编译时报错

### ISSUE THREAD

**Issue by Louie-Wong** [owent/libcopp#20]
OS: ubuntu18.04
Compiler: gcc 11.1.0
安装方式: ./vcpkg install libcopp:x64-linux
项目Cmake配置
target_link_libraries(NFMasterServerPlugin libcopp.a)
target_link_libraries(NFMasterServerPlugin libcotask.a)
报错信息
<img width="1030" alt="err" src="https://user-images.githubusercontent.com/71060355/126063937-a36f6675-ca59-4c7b-8e29-4c9f1d1948cf.png">

**Comment by owent** [comment]
@Louie-Wong

如果 `NFMasterServerPlugin` 是一个可执行程序,请使用 `target_link_libraries(NFMasterServerPlugin libcopp::cotask)`  。
如果 `NFMasterServerPlugin` 是一个库,请使用 `target_link_libraries(NFMasterServerPlugin PUBLIC libcopp::cotask)`  。
链接 `libcopp::cotask` 会自动设置依赖关系和包含目录。

如果一定要是用老的链接方式的话，需要先链接 libcotask 再链接 libcopp。即

```cmake
target_link_libraries(NFMasterServerPlugin libcotask.a libcopp.a)
```

这样的顺序。因为cotask依赖copp，C++写前面的会后链接。

**Comment by Louie-Wong** [comment]
好的，感谢， 好了
