### ISSUE TITLE
能支持一下 xmake 这个工具吗？

### ISSUE THREAD

**Issue by car520120** [owent/libcopp#21]
cmake 的语法实在不想去读，写起来也有一点怪怪的！特别是依赖多了以后

**Comment by owent** [comment]
> 
> 
> cmake 的语法实在不想去读，写起来也有一点怪怪的！特别是依赖多了以后

我看了下xmake的文档说是支持vcpkg啊，那应该可以直接用啊。类似 `add_requires("vcpkg::libcopp")` 这种。

**Comment by car520120** [comment]
类似的写法还是有一点非主流的，后面有空我自己试一下写一下吧，主要是不知道那些文件是和平台有关！能给一份文档吗？不同平台需要定义那些宏和还特定平台的特定文件有那些

**Comment by owent** [comment]
> 
> 
> 类似的写法还是有一点非主流的，后面有空我自己试一下写一下吧，主要是不知道那些文件是和平台有关！能给一份文档吗？不同平台需要定义那些宏和还特定平台的特定文件有那些

编译器和链接器相关: https://github.com/owent/libcopp/tree/v2/src/libcopp/fcontext
编译选项相关: https://github.com/owent/libcopp/blob/v2/project/cmake/ProjectBuildOption.cmake 和 https://github.com/owent/libcopp/blob/v2/CMakeLists.txt#L184
编译环境和编译器支持相关: https://github.com/atframework/cmake-toolset/blob/main/CompilerOption.cmake
