### ISSUE TITLE
如何在项目中直接使用libcopp源码？

### ISSUE THREAD

**Issue by speedster** [owent/libcopp#37]
我想在项目中以源码形式使用，应该引入哪些文件？

**Comment by owent** [comment]
直接cmake里 `add_subdirectory(<libcopp>目录)`

然后需要使用的工程里 `target_link_libraries(TARGET cotask)` 就可以了

**Comment by speedster** [comment]
支持交叉编译吗？我用arm-linux-gnueabihf-g++编译器，貌似不好使。

**Comment by owent** [comment]
> 支持交叉编译吗？我用arm-linux-gnueabihf-g++编译器，貌似不好使。

可以，交叉编译到ARM的话可能需要手动设置工具链（ https://github.com/owent/libcopp/blob/v2/src/libcopp/fcontext/detect/fcontext.detect.cmake 这里面涉及的几个变量）。
这个检测脚本比较老了，特别是Android NDK的一些变量结构变化很大。可能适配上不一定对。
如果呦问题，欢迎反馈。
