### ISSUE TITLE
请教关于开启协程的问题

### ISSUE THREAD

**Issue by seventeenman** [owent/libcopp#42]
**Description of your problem.**
作者你好，请教一下在开启协程执行一个函数的时候，如何向该函数传递参数呢，我只在example中看到参数为void *

**Describe the solution you'd like**
我想在一个while循环中开启协程执行`std::size_t copy_buffer(boost::asio::ip::tcp::socket &write_dst, boost::asio::ip::tcp::socket &read_src)`函数
我想实现的功能伪代码如下:
```
void relay(boost::asio::ip::tcp::socket &dst, boost::asio::ip::tcp::socket &src) {
    copp::coroutine_context_default::ptr_t co_obj_to = copp::coroutine_context_default::create(copy_buffer(dst, src));
    copp::coroutine_context_default::ptr_t co_obj_from = copp::coroutine_context_default::create(copy_buffer(src, dst));
    while (true){
        co_obj_to->start();
        co_obj_from->start();
    }
}
```

**Comment by owent** [comment]
这个 `void *` 就是用来传递参数的。`start(void*)` 传入的 `void*` 会传给入口函数或仿函数 `int operator()(void*)` 的参数。
`resume(void*)` 传入的 `void*` 会传给 `yield(void**)` 接口指向的指针。

你上面贴的通过仿函数去传递私有数据也是可以的，`copy_buffer()` 返回一个对象，实现 `int operator()(void*)` 和移动构造函数即可。然后其他的数据可以通过你自己的仿函数对象自由处理。

**Comment by seventeenman** [comment]
请问您的意思是指这样嘛
```
#include <libcopp/coroutine/coroutine_context_container.h>

// define a coroutine runner
class my_runner {
private:
    int _a;
    int _b;
public:
    my_runner()  {
        set_runner(1,2);
        get_runner();
    }

    void set_runner(int a,int b){
        _a = a;
        _b = b;
    }

    void get_runner(){
        std::cout << _a << _b << std::endl;
    }

    int operator()(void*) {
        return 1;
    }
};
int main() {
    copp::coroutine_context_default::ptr_t co_obj = copp::coroutine_context_default::create(my_runner());
    std::cout << "cortoutine " << co_obj.get() << " is created." << std::endl;

    // start a coroutine
    co_obj->start();

    return 0;
}
```

**Comment by owent** [comment]
> 请问您的意思是指这样嘛
> 
> ```
> #include <libcopp/coroutine/coroutine_context_container.h>
> 
> // define a coroutine runner
> class my_runner {
> private:
>     int _a;
>     int _b;
> public:
>     my_runner()  {
>         set_runner(1,2);
>         get_runner();
>     }
> 
>     void set_runner(int a,int b){
>         _a = a;
>         _b = b;
>     }
> 
>     void get_runner(){
>         std::cout << _a << _b << std::endl;
>     }
> 
>     int operator()(void*) {
>         return 1;
>     }
> };
> int main() {
>     copp::coroutine_context_default::ptr_t co_obj = copp::coroutine_context_default::create(my_runner());
>     std::cout << "cortoutine " << co_obj.get() << " is created." << std::endl;
> 
>     // start a coroutine
>     co_obj->start();
> 
>     return 0;
> }
> ```

对，第二种通过仿函数去传递是这样。
第一种通过参数传递会涉及数据转移和void*的类型转换，不用写完整的类。
你觉得哪种方便就用哪种呗。
