### ISSUE TITLE
Windows CMake 编译报错：Unknown CMake command "echowithcolor"

### ISSUE THREAD

**Issue by lijie512917227** [owent/libcopp#53]
**Description of your problem.**
在Windows上用CMake(3.27.1) 编译最新版本2.2.0报错：Unknown CMake command "echowithcolor"
构建命令：cmake .. -DPROJECT_ENABLE_UNITTEST=YES -DPROJECT_ENABLE_SAMPLE=YES

**Describe the solution you'd like**

**Comment by owent** [comment]
`git submodule update --init` 拉过子模块了吗？

**Comment by lijie512917227** [comment]
感谢回复，我用vcpkg安装了。

**Comment by owent** [comment]
vcpkg的版本好久没更新了。等晚点啥时候有空我去更新下。
